# version: '3.9'

# services:
#   mysql-db:
#     # NOTE: Uncomment the line below if you are using Mac with m1/m2 chip
#     platform: linux/x86_64
#     container_name: mysql-db
#     image: mysql:8.4
#     restart: always
#     command: mysqld --default-authentication-plugin=mysql_native_password
#     ports:
#       - 3306:3306
#     environment:
#       - MYSQL_DATABASE=localdb
#       - MYSQL_ROOT_PASSWORD=root
#     volumes:
#       - ./docker/database/mysql/init.sql:/var/lib/mysql/init.sql
#       # - ./database/nest:/var/lib/mysql
#       - mysql-volume:/var/lib/mysql:rw
#       - ./mysql-db:/docker-entrypoint-initdb.d/
#     networks:
#       - local-network

# volumes: 
#   mysql-volume:
  
# networks:
#   local-network:


version: '3.8'
services:
  mysql-db:
    platform: linux/x86_64 # if using Apple M1/M2 chip
    image: mysql:latest
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'localdb'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./scripts/mysql:/docker-entrypoint-initdb.d 
    networks:
      - local-network

volumes:
  mysql-volume:

networks:
  local-network:
    driver: bridge